### ISSUE TITLE
Unable to compile the plugin in UnrealEngine 4.22

### ISSUE THREAD

**Issue by zipzit** [fivefingergames/TwitchAuth#26]
This is some pretty awesome work.  I'm trying to understand how to compile the plugin.  I'm looking at the [Package.bat](https://github.com/mrbandler/TwitchAuth/blob/master/Package.bat) file, but I'm totally unable to compile any binaries.  With a bit of help from [this reference](https://wiki.unrealengine.com/How_To_Package_Plugins_For_UE4_Marketplace), I understand what you are doing, but I'm guessing your RunUAT.bat file using your path name, may be pointing to a much different version then I'm using?  My batch file:

   `rem Build the plugin`
   `call "C:\Program Files\Epic Games\UE_4.22\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -Plugin="%CD%\TwitchAuth.uplugin" -Package="%CD%\Build\TwitchAuth" -Rocket`

`rem Zip the plugin`
`rd /s /q "./Build/TwitchAuth/Intermediate"`
`rd /s /q "./Build/TwitchAuth/Binaries"`
`rem 7z a ./Build/TwitchAuth.zip ./Build/TwitchAuth/*`

`pause`

I've tried both UE 4.21 and 4.22, both seem to fail.  Log files really aren't much help.  
[UBT-UE4Editor-Win64-Development.txt](https://github.com/mrbandler/TwitchAuth/files/3096042/UBT-UE4Editor-Win64-Development.txt)
[Log.txt](https://github.com/mrbandler/TwitchAuth/files/3096043/Log.txt)

Where is your %path% stuff for RunUAT.bat pointing to?  Are you able to compile the repo, using UE 4.22 RunUAT.bat 

I will say, the generated Build folder is pretty bizarre.  Lots of subdirectories and repeats.  Is that correct?  Its also not clear to me that the Package.bat file here will result in the content I see downloaded via the Unreal Marketplace (ref: C:\Program Files\Epic Games\UE_4.22\Engine\Plugins\Marketplace\TwitchAuth)  ... but without a completed run, its not clear to me on how this works.  

By the way, many thanks for all the work you've put into this.  I never realized it was possible to insert usage example content into a plugin quite this way.  Nicely done.

**Comment by mrbandler** [comment]
First of all, thank you for using it! 😄

A bit of background first, the batch file ``RunUAT.bat`` actually just creates a host project and adds the plugin code to the ``Plugins`` sub-folder, like in any other UE4 project. After that, it tries to compile the project like you would in VS2017/VS2019.

What I do, after that has completed, is removing the ``Intermediate`` and ``Binaries`` folder, because Epic Games doesn't like them when I submit a new build to the UE4 Marketplace.

So basically what this ``Package.bat`` file does for me is just a final test that everything compiles and then zipping it up for me to upload to GitHub as a release and use that link to submit to the UE4 Marketplace. The actual content of the zip is basically just the ``Source``, ``Content`` and ``Resources`` folder every plugin should have, incl. the ``.uplugin`` file.

That said, if you want to use the plugin from the GitHub source you would only have to put the sources downloaded from GitHub into the sub-folder ``Plugins`` on any of your UE4 projects, on startup the engine would compile the plugin.

---

Now to the weird thing, why doesn't it compile on your end @zipzit?
It was the right call to point to the ``RunUAT.bat`` in your UE4 installation, I just used an environment variable for that, that's why it works without the absolute path.
I recently switch to VS2019 but that shouldn't be a problem as the code is compiler agnostic.

From the logs, you attached, it looks like the UnrealHeaderTool (UHT) is parsing the headers correctly but then the compiler is unable to spawn child processes. Are you able to build any of your other C++ UE4 projects within VS2107?
Maybe try running the ``Package.bat`` as Administrator?
